name: Django CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        django-version: [3.2, 4.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-testing.txt')}}-${{ hashFiles('tox.ini') }}-${{ matrix.python-version }}-${{ matrix.django-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        echo ${{ matrix.django-version }} > requirements-django${{ matrix.django-version }}.txt
        pip install -r requirements.txt -r requirements-testing.txt -c requirements-django${{ matrix.django-version }}.txt
    - name: Run Tests
      run: |
        make test
